#!/bin/bash
#SBATCH -t 5-00:00:00
#SBATCH -N 2 --ntasks-per-node=8
#SBATCH -n 16
#SBATCH --mail-user=roberto.ramos@unesp.br --mail-type=BEGIN,END,FAIL
#SBATCH -o job_kmesh_stress.out
#SBATCH -e job_kmesh_stress.error
#SBATCH -J TiO2-kmesh-stress

ulimit -s unlimited
ulimit -l unlimited
ulimit -a

module purge
module load miniconda
module load cp2k/2026.1        # <-- ADJUST to the exact CP2K module on your cluster

# ==========================================================
# ⚙️  RUNTIME CONFIG
# ==========================================================
CP2K_EXE="cp2k.psmp"
export CP2K_DATA_DIR="$CP2K_DATA"   

# CP2K 2026.1 is linked against its own toolchain MPICH 4.3.2 (not Intel MPI):
# plain `srun` (no --mpi plugin) started N independent 1-rank copies of the
# same run, all writing the same .out ("message passing processes 1"). MPICH's
# own mpiexec (Hydra, SLURM-aware) launches one real N-rank job.
check_mpi_ranks() {
    local n
    n=$(grep -m1 "Total number of message passing processes" "$1" 2>/dev/null | awk '{print $NF}')
    if [ "$n" != "$SLURM_NTASKS" ]; then
        echo "[WARNING] $1 reports ${n:-?} MPI ranks but SLURM_NTASKS=$SLURM_NTASKS -- launcher/MPI mismatch." >&2
    fi
}
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK #limits the number of threads used 
export MKL_NUM_THREADS=$SLURM_CPUS_PER_TASK
export OMP_PLACES=cores #avoids hyper-threading
export OMP_PROC_BIND=close #putz processes in the nearest cores available# module only sets CP2K_DATA; cp2k.psmp reads CP2K_DATA_DIR

# CP2K prints this banner when GEO_OPT/CELL_OPT converges normally -- but an
# ENERGY_FORCE (single-point) input never runs an optimizer at all, so this
# banner would never appear even on a perfectly good run. The right success
# criterion depends on RUN_TYPE, which is detected per-input below (defense
# in depth in case this ever points at a non-CELL_OPT scan directory).
OPT_CONVERGED_PATTERN="OPTIMIZATION COMPLETED"
SCF_CONVERGED_PATTERN="outer SCF loop converged"
ENDED_PATTERN="PROGRAM ENDED AT"

# ==========================================================
# 📂 DIRECTORY MANAGEMENT (For Central Script Library Use)
# ==========================================================
# Allows execution like: sbatch ~/scripts/job_kmesh_stress_convergence.sh /path/to/kmesh_stress_convergence
# Expects the tree already generated by kmesh_stress_convergence.py (one subdir per k-mesh).
SCAN_DIR=${1:-$SLURM_SUBMIT_DIR/kmesh_stress_convergence}
cd "$SCAN_DIR" || { echo "[ERROR] Scan directory not found: $SCAN_DIR"; exit 1; }

# ==========================================================
# 🚀 MAIN LOOP over k{kx}-{ky}-{kz}/ subdirectories
# ==========================================================
for run_dir in */; do
    run_dir=${run_dir%/}
    cd "$run_dir" || continue

    orig_inp=$(ls -- *.inp 2>/dev/null | head -1)
    if [ -z "$orig_inp" ]; then
        echo "[WARNING] No .inp file found in $run_dir, skipping."
        cd ..
        continue
    fi

    project_name="${orig_inp%.inp}"
    out_file="${orig_inp}.out"
    restart_file="${project_name}-1.restart"

    run_type=$(awk '/^[[:space:]]*RUN_TYPE[[:space:]]/{print $2; exit}' "$orig_inp")
    is_converged() {
        local f="$1"
        if [ "$run_type" = "CELL_OPT" ] || [ "$run_type" = "GEO_OPT" ]; then
            grep -q "$OPT_CONVERGED_PATTERN" "$f"
        else
            grep -q "$ENDED_PATTERN" "$f" && grep -q "$SCF_CONVERGED_PATTERN" "$f"
        fi
    }

    # --- Already converged from a previous submission? Skip. ---
    if [ -s "$out_file" ] && is_converged "$out_file"; then
        echo "[SUCCESS] $run_dir already converged. Skipping."
        echo "$run_dir: OK (recovered)" >> ../calculation.dat
        cd ..
        continue
    fi

    # --- Restart protocol (CP2K equivalent of cp CONTCAR POSCAR): -----------
    # If a .restart file exists from an interrupted run, it IS a full valid
    # CP2K input (last converged cell + coordinates + step counter) -- just
    # run it directly instead of the original .inp.
    if [ -s "$restart_file" ]; then
        echo "[INFO] Found restart checkpoint for $run_dir. Resuming from $restart_file."
        run_input="$restart_file"
    else
        echo "[INFO] No restart checkpoint found for $run_dir. Starting fresh."
        run_input="$orig_inp"
    fi

    echo "[INFO] Running k-mesh stress point: $run_dir (input: $run_input)"
    {
        echo "-------------------------------------------"
        echo "  CP2K K-mesh Stress Convergence -- $run_dir"
        echo "-------------------------------------------"
        echo " This job is running in dir: $(pwd)"
        echo " Using input: $run_input"
        echo " Starting: $(date +%Hh-%Mmin-%Ss--%Y/%m/%d)"
        echo "-------------------------------------------"
    } > step.log

    mpiexec -n "$SLURM_NTASKS" "$CP2K_EXE" -i "$run_input" -o "$out_file"

    check_mpi_ranks "$out_file"
    {
        echo "-------------------------------------------"
        echo " End: $(date +%Hh-%Mmin-%Ss--%Y/%m/%d)"
        echo "-------------------------------------------"
    } >> step.log

    if is_converged "$out_file"; then
        echo "[INFO] $run_dir converged."
        echo "$run_dir: OK" >> ../calculation.dat
    elif [ -s "$restart_file" ]; then
        echo "[INFO] $run_dir did not converge yet but wrote a restart checkpoint -- "
        echo "       resubmit this job to continue from $restart_file."
        echo "$run_dir: IN_PROGRESS (restart checkpoint available)" >> ../calculation.dat
    else
        echo "[WARNING] $run_dir did not converge and produced no restart checkpoint -- check $out_file."
        echo "$run_dir: FAILED" >> ../calculation.dat
    fi

    cd ..
done

echo "[INFO] K-mesh stress convergence scan finished (or partially finished -- check calculation.dat)."
echo "[INFO] Resubmit this same job to continue any IN_PROGRESS points."
echo "[INFO] Parse converged results with:"
echo "  python ~/scripts/parse_kmesh_stress_convergence.py --scan-dir $SCAN_DIR --n-atoms <N_ATOMS>"