#!/bin/bash
#SBATCH -t 24:00:00
#SBATCH -N 1 --ntasks-per-node=32
#SBATCH -n 32
#SBATCH --partition=short
#SBATCH --mem=64G
#SBATCH --mail-user=robeerto.aguiar.ramos@gmail.com
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH -o job_cutoffconv.out
#SBATCH -e job_cutoffconv.error
#SBATCH -J TiO2-cutoffconv

ulimit -s unlimited
ulimit -l unlimited
ulimit -a

module purge
module load miniconda
module load cp2k/2026.1      # <-- ADJUST to the exact CP2K module on your cluster

# ==========================================================
# ⚙️  RUNTIME CONFIG
# ==========================================================
CP2K_EXE="cp2k.psmp"
export CP2K_DATA_DIR="$CP2K_DATA"   

# CP2K 2026.1 is linked against its own toolchain MPICH 4.3.2 (not Intel MPI):
# plain `srun` (no --mpi plugin) started N independent 1-rank copies of the
# same run, all writing the same .out ("message passing processes 1"). MPICH's
# own mpiexec (Hydra, SLURM-aware) launches one real N-rank job.
check_mpi_ranks() {
    local n
    n=$(grep -m1 "Total number of message passing processes" "$1" 2>/dev/null | awk '{print $NF}')
    if [ "$n" != "$SLURM_NTASKS" ]; then
        echo "[WARNING] $1 reports ${n:-?} MPI ranks but SLURM_NTASKS=$SLURM_NTASKS -- launcher/MPI mismatch." >&2
    fi
}
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK #limits the number of threads used 
export MKL_NUM_THREADS=$SLURM_CPUS_PER_TASK
export OMP_PLACES=cores #avoids hyper-threading
export OMP_PROC_BIND=close #putz processes in the nearest cores available# module only sets CP2K_DATA; cp2k.psmp reads CP2K_DATA_DIR

# ==========================================================
# 📂 DIRECTORY MANAGEMENT (For Central Script Library Use)
# ==========================================================
# Allows execution like: sbatch ~/scripts/job_cutoff_convergence.sh /path/to/cutoff_convergence
# Expects the tree already generated by cutoff_convergence.py (one subdir per CUTOFF value).
SCAN_DIR=${1:-$SLURM_SUBMIT_DIR/cutoff_convergence}
cd "$SCAN_DIR" || { echo "[ERROR] Scan directory not found: $SCAN_DIR"; exit 1; }

# ==========================================================
# 🚀 MAIN LOOP over cutoffNNN/ subdirectories
# ==========================================================
for run_dir in */; do
    run_dir=${run_dir%/}
    cd "$run_dir" || continue

    inp_file=$(ls -- *.inp 2>/dev/null | head -1)

    if [ -z "$inp_file" ]; then
        echo "[WARNING] No .inp file found in $run_dir, skipping."
        cd ..
        continue
    fi

    out_file="${inp_file}.out"

    # --- Restart protocol: skip runs that already finished normally.
    # "PROGRAM ENDED AT" only means CP2K exited without crashing -- CP2K
    # does NOT abort on SCF non-convergence, it just prints the unconverged
    # energy and moves on. Require the explicit outer-SCF convergence line
    # too, or a silently-unconverged run would be skipped as "done" forever.
    if [ -s "$out_file" ] && grep -q "PROGRAM ENDED AT" "$out_file" \
       && grep -q "outer SCF loop converged" "$out_file"; then
        echo "[SUCCESS] $run_dir already completed. Skipping."
        echo "$run_dir: OK (recovered)" >> ../calculation.dat
        cd ..
        continue
    fi

    echo "[INFO] Running CUTOFF scan point: $run_dir"
    {
        echo "-------------------------------------------"
        echo "  CP2K Cutoff Convergence -- $run_dir"
        echo "-------------------------------------------"
        echo " This job is running in dir: $(pwd)"
        echo " Starting: $(date +%Hh-%Mmin-%Ss--%Y/%m/%d)"
        echo "-------------------------------------------"
    } > step.log

    mpiexec -n "$SLURM_NTASKS" "$CP2K_EXE" -i "$inp_file" -o "$out_file"

    check_mpi_ranks "$out_file"
    {
        echo "-------------------------------------------"
        echo " End: $(date +%Hh-%Mmin-%Ss--%Y/%m/%d)"
        echo "-------------------------------------------"
    } >> step.log

    if ! grep -q "PROGRAM ENDED AT" "$out_file"; then
        echo "[WARNING] $run_dir did not report normal CP2K termination -- check $out_file."
        echo "$run_dir: FAILED (crash/abort)" >> ../calculation.dat
    elif ! grep -q "outer SCF loop converged" "$out_file"; then
        echo "[WARNING] $run_dir ran to completion but the SCF did NOT converge -- check $out_file."
        echo "$run_dir: FAILED (SCF not converged)" >> ../calculation.dat
    else
        echo "[INFO] $run_dir finished normally and SCF converged."
        echo "$run_dir: OK" >> ../calculation.dat
    fi

    cd ..
done

echo "[INFO] Cutoff convergence scan finished."
echo "[INFO] Parse results with:"
echo "  python ~/scripts/parse_cutoff_convergence.py --scan-dir $SCAN_DIR --n-atoms <N_ATOMS>"