#!/usr/bin/env python3
"""
parse_kmesh_stress_convergence.py

Parses the outputs of a rigorous k-mesh CELL_OPT ("stress") convergence scan
(as generated by kmesh_stress_convergence.py and run by
job_kmesh_stress_convergence.sh). For each k-mesh, extracts:

  - the final (relaxed) total energy from the .out file
  - the final (relaxed) cell volume from the .restart file's &CELL block

and reports both convergence deltas (meV/atom and % volume) relative to the
densest mesh tested -- this is the CP2K analog of watching the VASP relaxed
volume stabilize across a KPOINTS scan.

Usage:
    python ~/scripts/parse_kmesh_stress_convergence.py \\
        --scan-dir kmesh_stress_convergence --n-atoms 6 \\
        --energy-threshold-mev-atom 1.0 --volume-threshold-pct 0.5
"""

import argparse
import re
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

ENERGY_PATTERN = re.compile(r"(?m)^\s*ENERGY\|\s+Total FORCE_EVAL.*\s(-?\d+\.\d+(?:[eE][-+]?\d+)?)\s*$")
KMESH_PATTERN = re.compile(r"MONKHORST-PACK\s+(\d+)\s+(\d+)\s+(\d+)")
CELL_VECTOR_PATTERN = re.compile(
    r"^\s*([ABC])\s+([-+\d.Ee]+)\s+([-+\d.Ee]+)\s+([-+\d.Ee]+)", re.MULTILINE
)

HARTREE_TO_MEV = 27211.386245988


def parse_args():
    parser = argparse.ArgumentParser(
        description="Parse and plot a rigorous k-mesh CELL_OPT (stress) convergence scan."
    )
    parser.add_argument("--scan-dir", type=str, default="kmesh_stress_convergence",
                         help="Root directory produced by kmesh_stress_convergence.py")
    parser.add_argument("--n-atoms", type=int, required=True,
                         help="Number of atoms in the cell (for the meV/atom criterion).")
    parser.add_argument("--energy-threshold-mev-atom", type=float, default=1.0)
    parser.add_argument("--volume-threshold-pct", type=float, default=0.5,
                         help="Relaxed-volume convergence threshold, in percent, "
                              "relative to the densest mesh tested.")
    parser.add_argument("--output-plot", type=str, default="kmesh_stress_convergence.png")
    return parser.parse_args()


def extract_energy_hartree(out_file: Path):
    text = out_file.read_text(errors="ignore")
    matches = ENERGY_PATTERN.findall(text)
    return float(matches[-1]) if matches else None


def cross(a, b):
    return (
        a[1] * b[2] - a[2] * b[1],
        a[2] * b[0] - a[0] * b[2],
        a[0] * b[1] - a[1] * b[0],
    )


def dot(a, b):
    return sum(x * y for x, y in zip(a, b))


def extract_volume_from_restart(restart_file: Path):
    """Parse the final &CELL A/B/C vectors from a CP2K .restart file and
    return the cell volume (angstrom^3) via the scalar triple product."""
    text = restart_file.read_text(errors="ignore")
    vectors = {}
    for m in CELL_VECTOR_PATTERN.finditer(text):
        label, x, y, z = m.groups()
        vectors[label] = (float(x), float(y), float(z))  # last match wins if repeated
    if not {"A", "B", "C"} <= vectors.keys():
        return None
    return abs(dot(vectors["A"], cross(vectors["B"], vectors["C"])))


def main():
    args = parse_args()
    scan_root = Path(args.scan_dir)
    if not scan_root.exists():
        raise SystemExit(f"ERROR: scan directory not found: {scan_root}")

    results = []  # list of dicts: mesh, energy_ha, volume_ang3
    for run_dir in sorted(scan_root.iterdir()):
        if not run_dir.is_dir():
            continue

        inp_files = list(run_dir.glob("*.inp"))
        out_files = list(run_dir.glob("*.inp.out")) + list(run_dir.glob("*.out"))
        restart_files = sorted(run_dir.glob("*-1.restart"))

        if not inp_files or not out_files:
            print(f"WARNING: missing .inp/.out in {run_dir}, skipping.")
            continue

        mesh = None
        m = KMESH_PATTERN.search(inp_files[0].read_text())
        if m:
            mesh = tuple(int(x) for x in m.groups())
        if mesh is None:
            print(f"WARNING: could not read k-mesh from {inp_files[0]}, skipping.")
            continue

        energy_ha = extract_energy_hartree(out_files[0])
        if energy_ha is None:
            print(f"WARNING: could not parse total energy in {out_files[0]}, skipping.")
            continue

        if not restart_files:
            print(f"WARNING: no .restart file in {run_dir} -- relaxation may not have "
                  f"produced a checkpoint yet (still running?). Skipping volume for this point.")
            volume = None
        else:
            volume = extract_volume_from_restart(restart_files[-1])
            if volume is None:
                print(f"WARNING: could not parse &CELL from {restart_files[-1]}, skipping volume.")

        results.append({"mesh": mesh, "energy_ha": energy_ha, "volume_ang3": volume})

    if not results:
        raise SystemExit("No results parsed. Check --scan-dir and that CP2K runs completed.")

    results.sort(key=lambda r: r["mesh"])

    labels = [f"{r['mesh'][0]}x{r['mesh'][1]}x{r['mesh'][2]}" for r in results]
    energies_ha = [r["energy_ha"] for r in results]
    volumes = [r["volume_ang3"] for r in results]

    # Reference point = mesh with the most total k-points, regardless of how
    # `results` is ordered for display. Volume falls back to the next-densest
    # mesh that actually produced a .restart, still ranked by density (not by
    # display order, which can disagree with density ranking).
    by_density = sorted(results, key=lambda r: r["mesh"][0] * r["mesh"][1] * r["mesh"][2])
    e_ref = by_density[-1]["energy_ha"]
    v_ref = next((r["volume_ang3"] for r in reversed(by_density) if r["volume_ang3"] is not None), None)

    delta_mev_atom = [(e - e_ref) * HARTREE_TO_MEV / args.n_atoms for e in energies_ha]
    delta_vol_pct = [
        (100.0 * (v - v_ref) / v_ref) if (v is not None and v_ref is not None) else None
        for v in volumes
    ]

    print(f"{'k-mesh':<10}{'E (Ha)':>16}{'dE (meV/atom)':>16}{'V (A^3)':>14}{'dV (%)':>10}")
    for label, e_ha, de, v, dv in zip(labels, energies_ha, delta_mev_atom, volumes, delta_vol_pct):
        v_str = f"{v:.3f}" if v is not None else "n/a"
        dv_str = f"{dv:+.3f}" if dv is not None else "n/a"
        print(f"{label:<10}{e_ha:>16.8f}{de:>16.4f}{v_str:>14}{dv_str:>10}")

    # Walk density-ascending (excluding the reference mesh itself) and keep
    # the earliest mesh that stays within both thresholds all the way up to
    # the reference -- a single lucky pass that regresses at higher density
    # does not count, which is what made the plain "first hit" flaky.
    densest_label = f"{by_density[-1]['mesh'][0]}x{by_density[-1]['mesh'][1]}x{by_density[-1]['mesh'][2]}"
    recommended = densest_label
    candidate = None
    for r in by_density[:-1]:
        label = f"{r['mesh'][0]}x{r['mesh'][1]}x{r['mesh'][2]}"
        de = (r["energy_ha"] - e_ref) * HARTREE_TO_MEV / args.n_atoms
        v = r["volume_ang3"]
        dv = (100.0 * (v - v_ref) / v_ref) if (v is not None and v_ref is not None) else None
        e_ok = abs(de) <= args.energy_threshold_mev_atom
        v_ok = (dv is not None) and (abs(dv) <= args.volume_threshold_pct)
        if e_ok and v_ok:
            if candidate is None:
                candidate = label
        else:
            candidate = None
    if candidate is not None:
        recommended = candidate

    print(f"\nRecommended k-mesh (least dense mesh that stays within {args.energy_threshold_mev_atom} "
          f"meV/atom AND {args.volume_threshold_pct}% volume of the densest mesh tested, all the way "
          f"up to it): {recommended}")
    print("This is the mesh to carry forward into the production GEO_OPT ('Etot') step.")

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 4))
    ax1.plot(labels, delta_mev_atom, marker="o", color="tab:blue")
    ax1.axhline(args.energy_threshold_mev_atom, color="gray", linestyle="--", linewidth=1)
    ax1.axhline(-args.energy_threshold_mev_atom, color="gray", linestyle="--", linewidth=1)
    ax1.set_xlabel("k-mesh")
    ax1.set_ylabel("ΔE relative to densest mesh (meV/atom)")
    ax1.set_title("Relaxed energy convergence")
    ax1.tick_params(axis="x", rotation=45)

    dv_plot = [dv if dv is not None else float("nan") for dv in delta_vol_pct]
    ax2.plot(labels, dv_plot, marker="o", color="tab:orange")
    ax2.axhline(args.volume_threshold_pct, color="gray", linestyle="--", linewidth=1)
    ax2.axhline(-args.volume_threshold_pct, color="gray", linestyle="--", linewidth=1)
    ax2.set_xlabel("k-mesh")
    ax2.set_ylabel("ΔVolume relative to densest mesh (%)")
    ax2.set_title("Relaxed volume convergence")
    ax2.tick_params(axis="x", rotation=45)

    fig.tight_layout()
    fig.savefig(args.output_plot, dpi=150)
    print(f"\nPlot saved to: {args.output_plot}")


if __name__ == "__main__":
    main()