#!/bin/bash
#SBATCH -J cp2k-scan
#SBATCH -p short
#SBATCH -t 1-00:00:00
#SBATCH -N 1
#SBATCH --ntasks-per-node=14
#SBATCH --cpus-per-task=2
#SBATCH --mem-per-cpu=2194M
#SBATCH -o scan_%A_%a.out
#SBATCH -e scan_%A_%a.err
#
# One array task per sub-directory of SCAN_DIR (steps 01, 02, and a batch of
# slabs from 07). Directories are taken in natural order (sort -V).
#   N=$(find SCAN_DIR -mindepth 1 -maxdepth 1 -type d | wc -l)
#   sbatch --array=0-$((N-1)) ~/work_cp2k/jobs/job_scan_array.sh SCAN_DIR
# Resubmitting the same command resumes unfinished points (restart-safe).
# Do not edit this file while tasks of an array are still pending: each task
# re-reads it when it starts.

source "$(dirname "$(readlink -f "$0")")/common.sh" 2>/dev/null || source ~/work_cp2k/jobs/common.sh

SCAN_DIR=$(readlink -f "${1:?usage: sbatch --array=0-N job_scan_array.sh SCAN_DIR}")
mapfile -t DIRS < <(find "$SCAN_DIR" -mindepth 1 -maxdepth 1 -type d ! -name '.*' | sort -V)
i=${SLURM_ARRAY_TASK_ID:?submit with --array}
[ "$i" -lt "${#DIRS[@]}" ] || { echo "[ERROR] index $i >= ${#DIRS[@]} dirs in $SCAN_DIR"; exit 1; }
run_dir "${DIRS[$i]}"
