#!/bin/bash
#SBATCH -J cp2k-scan
#SBATCH -p short
#SBATCH -t 1-00:00:00
#SBATCH -N 1
#SBATCH --ntasks-per-node=14
#SBATCH --cpus-per-task=2
#SBATCH --mem-per-cpu=2194M
#SBATCH -o scan_%A_%a.out
#SBATCH -e scan_%A_%a.err
#
# One array task per sub-directory of SCAN_DIR (steps 01, 02, and a batch of
# slabs from 07). Directories are taken in natural order (sort -V).
#   N=$(find SCAN_DIR -mindepth 1 -maxdepth 1 -type d | wc -l)
#   sbatch --array=0-$((N-1)) ~/work_cp2k/jobs/job_scan_array.sh SCAN_DIR
# or a LIST_FILE with one run directory per line (task i = line i, comments skipped).
# Resubmitting the same command resumes unfinished points (restart-safe).
# Do not edit this file while tasks of an array are still pending: each task
# re-reads it when it starts.

for _c in "$(dirname "$(readlink -f "$0")")" "${CP2K_SCRIPTS:-/nonexistent}/jobs" ~/work_cp2k/jobs ~/work_cp2k/cp2k_scripts/jobs; do
    [ -s "$_c/common.sh" ] && grep -q "^run_dir()" "$_c/common.sh" && { source "$_c/common.sh"; break; }
done
declare -F run_dir >/dev/null || { echo "[ERROR] jobs/common.sh not found (set CP2K_SCRIPTS=<repo>)"; exit 2; }

SCAN=$(readlink -f "${1:?usage: sbatch --array=0-N job_scan_array.sh SCAN_DIR|LIST_FILE}")
if [ -f "$SCAN" ]; then    # list file: one run directory per line (# comments, blank lines ignored)
    mapfile -t DIRS < <(grep -v -E '^\s*(#|$)' "$SCAN")
else
    mapfile -t DIRS < <(find "$SCAN" -mindepth 1 -maxdepth 1 -type d ! -name '.*' | sort -V)
fi
i=${SLURM_ARRAY_TASK_ID:?submit with --array}
[ "$i" -lt "${#DIRS[@]}" ] || { echo "[ERROR] index $i >= ${#DIRS[@]} dirs in $SCAN"; exit 1; }
run_dir "${DIRS[$i]}"
